#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl stop squidstats.service 2>/dev/null || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
