#!/usr/bin/env python3
"""
Comprehensive Spanish→English translation for SquidStats .po file.
Handles: already-English strings, Spanish UI strings, technical strings.
"""

import re
import sys

# ── Complete Spanish→English dictionary ──────────────────────────────
TRANSLATIONS = {
    # ── Navigation & general UI ──
    "Inicio": "Home",
    "Estadísticas": "Statistics",
    "Usuarios": "Users",
    "Reportes": "Reports",
    "Auditoría": "Audit",
    "Blacklist": "Blacklist",
    "Admin": "Admin",
    "Configuración": "Configuration",
    "Acciones": "Actions",
    "Estado": "Status",
    "Buscar": "Search",
    "Buscar...": "Search...",
    "Filtrar": "Filter",
    "Limpiar": "Clear",
    "Cerrar": "Close",
    "Guardar": "Save",
    "Cancelar": "Cancel",
    "Eliminar": "Delete",
    "Editar": "Edit",
    "Crear": "Create",
    "Agregar": "Add",
    "Actualizar": "Update",
    "Volver": "Back",
    "Enviar": "Send",
    "Aceptar": "Accept",
    "Confirmar": "Confirm",
    "Descargar": "Download",
    "Cargar": "Load",
    "Subir": "Upload",
    "Ver": "View",
    "Mostrar": "Show",
    "Ocultar": "Hide",
    "Activar": "Enable",
    "Desactivar": "Disable",
    "Sí": "Yes",
    "No": "No",
    "Todos": "All",
    "Ninguno": "None",
    "Anterior": "Previous",
    "Siguiente": "Next",
    "Primero": "First",
    "Último": "Last",
    "Cargando...": "Loading...",
    "Procesando...": "Processing...",
    "Exportar": "Export",
    "Importar": "Import",
    "Bloquear": "Block",
    "Desbloquear": "Unblock",
    "Seleccionar": "Select",
    # ── Auth ──
    "Iniciar sesión": "Log In",
    "Iniciar Sesión": "Log In",
    "Cerrar sesión": "Log Out",
    "Contraseña": "Password",
    "Usuario": "User",
    "Nombre de usuario": "Username",
    "Recordarme": "Remember me",
    "Recuérdame": "Remember me",
    "Has cerrado sesión correctamente.": "You have logged out successfully.",
    "¡Bienvenido, %(username)s!": "Welcome, %(username)s!",
    "Bienvenido a SquidStats": "Welcome to SquidStats",
    "Ingresa tus credenciales para acceder al sistema": "Enter your credentials to access the system",
    "Ingresa tu contraseña": "Enter your password",
    "Ingresa tu usuario": "Enter your username",
    "Login - SquidStats Admin": "Login - SquidStats Admin",
    "Inicia sesión con una cuenta de administrador para acceder a esta sección.": "Log in with an administrator account to access this section.",
    "Necesitas iniciar sesión como admin.": "You need to log in as admin.",
    "Por favor, inicia sesión para acceder a esta página.": "Please log in to access this page.",
    "No tienes permisos para acceder a esta página.": "You do not have permission to access this page.",
    "Conexión segura con JWT": "Secure connection with JWT",
    "La contraseña debe tener al menos 8 caracteres": "Password must be at least 8 characters",
    "Autenticación": "Authentication",
    "Contraseña Bind": "Bind Password",
    # ── Status ──
    "Activo": "Active",
    "Inactivo": "Inactive",
    "Inactiva": "Inactive",
    "Habilitado": "Enabled",
    "Deshabilitado": "Disabled",
    "Conectado": "Connected",
    "Desconectado": "Disconnected",
    "En línea": "Online",
    "Fuera de línea": "Offline",
    "Nunca": "Never",
    "Pendiente": "Pending",
    "Completado": "Completed",
    "Fallido": "Failed",
    "Normal": "Normal",
    "Excedido": "Exceeded",
    "Cargada": "Loaded",
    "No cargada": "Not loaded",
    # ── Table headers & labels ──
    "Nombre": "Name",
    "Descripción": "Description",
    "Fecha": "Date",
    "Hora": "Time",
    "Tipo": "Type",
    "Tamaño": "Size",
    "Rol": "Role",
    "IP": "IP",
    "Puerto": "Port",
    "Dominio": "Domain",
    "Dominios": "Domains",
    "URL": "URL",
    "Origen": "Source",
    "Destino": "Destination",
    "Protocolo": "Protocol",
    "Método": "Method",
    "Resultado": "Result",
    "Total": "Total",
    "Promedio": "Average",
    "Máximo": "Maximum",
    "Mínimo": "Minimum",
    "Detalles": "Details",
    "Resumen": "Summary",
    "Último Login": "Last Login",
    "Última conexión": "Last Connection",
    "Fecha de creación": "Creation Date",
    "ID": "ID",
    "General": "General",
    "Detalle": "Detail",
    "Conteo": "Count",
    "Duración": "Duration",
    "Valor:": "Value:",
    "Código": "Code",
    "Datos": "Data",
    "Grupo": "Group",
    "Grupos": "Groups",
    "Pool": "Pool",
    "Clase": "Class",
    "Motor": "Engine",
    "Registro": "Record",
    "Archivo": "File",
    "Tablas": "Tables",
    "Tabla": "Table",
    "Frecuencia": "Frequency",
    "Departamento": "Department",
    # ── Admin sections ──
    "Gestión de Usuarios": "User Management",
    "Gestionar Usuarios": "Manage Users",
    "Crear Usuario": "Create User",
    "Editar Usuario": "Edit User",
    "Eliminar Usuario": "Delete User",
    "Panel de Administración": "Administration Panel",
    "Panel de administración del sistema": "System administration panel",
    "Dashboard": "Dashboard",
    "Dashboard Admin": "Admin Dashboard",
    "Dashboard - Resumen del Sistema": "Dashboard - System Summary",
    "Configuración de Squid": "Squid Configuration",
    "Configuración del Sistema": "System Configuration",
    "Variables de Entorno": "Environment Variables",
    "Base de Datos": "Database",
    "Gestión de Base de Datos": "Database Management",
    "Respaldo": "Backup",
    "Respaldos": "Backups",
    "Sistema": "System",
    "Logs": "Logs",
    "Registros": "Records",
    "Registros de Log": "Log Records",
    "Registros Totales": "Total Records",
    "Notificaciones": "Notifications",
    "Reglas de Acceso": "Access Rules",
    "Listas de Control de Acceso": "Access Control Lists",
    "ACLs": "ACLs",
    "Delay Pools": "Delay Pools",
    "Cuotas": "Quotas",
    "Seguridad": "Security",
    "Configuración de Base de Datos": "Database Configuration",
    "Configuración de Proxy": "Proxy Configuration",
    "Configuración de Salvas": "Backup Configuration",
    "Configuración de Seguridad": "Security Configuration",
    "Configuración de Telegram": "Telegram Configuration",
    "Configuración de conexión": "Connection Configuration",
    "Configuraciones LDAP/Active Directory": "LDAP/Active Directory Settings",
    "Admin Squid": "Squid Admin",
    "Administrador": "Administrator",
    "Administrador Squid Proxy": "Squid Proxy Administrator",
    # ── Dashboard ──
    "Panel principal con conexiones activas": "Main panel with active connections",
    "Conexiones Activas": "Active Connections",
    "Conexiones Totales": "Total Connections",
    "Conexiones totales de este usuario": "Total connections for this user",
    "Tráfico Total": "Total Traffic",
    "Tráfico de Red": "Network Traffic",
    "Uso de CPU": "CPU Usage",
    "Uso de Memoria": "Memory Usage",
    "Disco": "Disk",
    "Espacio en Disco": "Disk Space",
    "Espacio Total": "Total Space",
    "Tiempo de Actividad": "Uptime",
    "Tiempo Activo": "Active Time",
    "Tiempo Encendido": "Uptime",
    "Versión de Squid": "Squid Version",
    "Estado Squid": "Squid Status",
    "Estado del Sistema": "System Status",
    "Servicio Squid": "Squid Service",
    "Servidor Squid:": "Squid Server:",
    "Gráficas del Sistema": "System Charts",
    "Estadísticas de Caché": "Cache Statistics",
    "Estadísticas de rendimiento del cache": "Cache performance statistics",
    "Estadísticas del Sistema": "System Statistics",
    "Usuarios Activos": "Active Users",
    "Usuarios Totales": "Total Users",
    "Usuarios bloqueados": "Blocked Users",
    "Usuarios únicos": "Unique Users",
    "Usuarios con cuota": "Users with Quota",
    "Total Usuarios": "Total Users",
    "Total Grupos": "Total Groups",
    "Total Salvas": "Total Backups",
    "Número de Usuarios": "Number of Users",
    "Usuario activo": "Active user",
    "Anónimo": "Anonymous",
    "Desconocido": "Unknown",
    "Dirección IP": "IP Address",
    "IP del Cliente": "Client IP",
    "Hora Local": "Local Time",
    "Zona Horaria": "Time Zone",
    "Sistema Operativo": "Operating System",
    "Tipo de Sistema": "System Type",
    # ── Blacklist ──
    "Gestión de Blacklist": "Blacklist Management",
    "Blacklist - Gestor de Listas": "Blacklist - List Manager",
    "Lista Negra": "Blacklist",
    "Lista Negra de Dominios": "Domain Blacklist",
    "Lista Personalizada": "Custom List",
    "Listas importadas": "Imported Lists",
    "Agregar Dominio": "Add Domain",
    "Agregar Lista": "Add List",
    "Importar Lista": "Import List",
    "Exportar Lista": "Export List",
    "Importar listas": "Import lists",
    "Importando lista": "Importing list",
    "Importando lista de bloqueo": "Importing block list",
    "Dominio bloqueado": "Blocked domain",
    "Dominio desbloqueado": "Unblocked domain",
    "Dominios bloqueados": "Blocked domains",
    "Fuente": "Source",
    "Todas las fuentes": "All sources",
    "URL de la lista": "List URL",
    "URL no proporcionada": "URL not provided",
    "Host de Pi-hole no proporcionado": "Pi-hole host not provided",
    "Blacklist actualizada exitosamente": "Blacklist updated successfully",
    "Lista personalizada vacía": "Custom list is empty",
    "Lista personalizada guardada en BLACKLIST_DOMAINS": "Custom list saved to BLACKLIST_DOMAINS",
    "Lista personalizada guardada y archivo custom de Squid actualizado": "Custom list saved and Squid custom file updated",
    "Sincronización de listas iniciada (en segundo plano)": "List synchronization started (in background)",
    "Lista importada desde URL correctamente": "List imported from URL successfully",
    "Archivo importado correctamente": "File imported successfully",
    "No se encontraron dominios para importar": "No domains found to import",
    "Eliminar lista y dominios": "Delete list and domains",
    "Sincronizar Listas": "Sync Lists",
    "Exportar archivo hosts": "Export hosts file",
    "Exporta o importa reglas en formato compatible con dnsmasq.": "Export or import rules in dnsmasq-compatible format.",
    "Importa desde archivos locales o pega URLs de listas públicas.": "Import from local files or paste public list URLs.",
    "Añade dominios manualmente o pega una lista separada por comas/lineas.": "Add domains manually or paste a comma/line separated list.",
    "Soporte para fuentes y listas públicas compatibles con AdGuard.": "Support for sources and public lists compatible with AdGuard.",
    "Sitios bloqueados y actividad restringida": "Blocked sites and restricted activity",
    "Validando URL y procesando dominios...": "Validating URL and processing domains...",
    "La blacklist contiene más de": "The blacklist contains more than",
    "Subir archivo": "Upload file",
    "Buscar bloqueado...": "Search blocked...",
    "Integración AdGuard": "AdGuard Integration",
    "Integración Pi-hole": "Pi-hole Integration",
    "Pi-hole Host": "Pi-hole Host",
    "Intentos Bloqueados": "Blocked Attempts",
    # ── Reports ──
    "Generar Reporte": "Generate Report",
    "Reporte Diario": "Daily Report",
    "Reporte Semanal": "Weekly Report",
    "Reporte Mensual": "Monthly Report",
    "Exportar PDF": "Export PDF",
    "Descargar PDF": "Download PDF",
    "Desde": "From",
    "Hasta": "To",
    "Rango de Fechas": "Date Range",
    "Sin datos disponibles": "No data available",
    "Sin datos": "No data",
    "No hay datos para el reporte": "No data for the report",
    "No hay datos disponibles para esta auditoría.": "No data available for this audit.",
    "Generando reporte...": "Generating report...",
    "Reporte listo": "Report ready",
    "Reportes SquidStats": "SquidStats Reports",
    "Reportes SquidStats -": "SquidStats Reports -",
    "Reportes y gráficas avanzadas": "Reports and advanced charts",
    "Fecha de Fin": "End Date",
    "Fecha del Reporte": "Report Date",
    "Fecha del reporte:": "Report date:",
    "Seleccione los filtros y genere un reporte": "Select filters and generate a report",
    "Rango:": "Range:",
    "Hoy": "Today",
    "Ayer": "Yesterday",
    "Últimos 7 días": "Last 7 days",
    "Últimos 30 días": "Last 30 days",
    "24 Horas": "24 Hours",
    # ── Logs ──
    "Registros del Sistema": "System Logs",
    "Ver Logs": "View Logs",
    "Registros de Acceso": "Access Logs",
    "Nivel": "Level",
    "Mensaje": "Message",
    "Componente": "Component",
    "Revisar logs del sistema": "Review system logs",
    "Buscar texto en los logs": "Search text in logs",
    "Líneas a mostrar:": "Lines to show:",
    "Mostrando últimas": "Showing last",
    "Mostrar:": "Show:",
    # ── Config ──
    "Variables de entorno guardadas exitosamente": "Environment variables saved successfully",
    "ID de ACL inválido": "Invalid ACL ID",
    "Índice de regla inválido": "Invalid rule index",
    "Error saving configuration": "Error saving configuration",
    "Error saving configuration: %(message)s": "Error saving configuration: %(message)s",
    "Error al procesar el archivo": "Error processing file",
    "Error al guardar blacklist": "Error saving blacklist",
    "Error al guardar la lista": "Error saving list",
    "Error al cargar la vista": "Error loading view",
    "Error importando desde URL: %(err)s": "Error importing from URL: %(err)s",
    "Error al procesar el archivo: %(error)s": "Error processing file: %(error)s",
    "Error al guardar blacklist: %(error)s": "Error saving blacklist: %(error)s",
    "Error al guardar la lista: %(error)s": "Error saving list: %(error)s",
    "Error al cargar la vista: %(error)s": "Error loading view: %(error)s",
    "Lista eliminada: %(url)s (%(count)s dominios)": "List deleted: %(url)s (%(count)s domains)",
    "Lista personalizada guardada en DB, pero no se pudo regenerar el archivo de Squid: %(msg)s": "Custom list saved to DB, but could not regenerate Squid file: %(msg)s",
    "Editar Configuración de Squid": "Edit Squid Configuration",
    "Editar squid.conf": "Edit squid.conf",
    "Contenido del archivo squid.conf:": "Contents of squid.conf file:",
    "Modificar archivo squid.conf": "Modify squid.conf file",
    "Modificar archivo squid.conf (deshabilitado)": "Modify squid.conf file (disabled)",
    "Guardar Configuración": "Save Configuration",
    "Gestionar Configuración Modular": "Manage Modular Configuration",
    "Gestión de Configuración de Squid": "Squid Configuration Management",
    "Editar Configuración": "Edit Configuration",
    "Ver Configuración": "View Configuration",
    "Dividir Configuración": "Split Configuration",
    "Dividir Configuración Squid": "Split Squid Configuration",
    "Dividir Squid Config": "Split Squid Config",
    "Configuración General": "General Configuration",
    "Restablecer": "Reset",
    "Aplicar": "Apply",
    "Recargar": "Reload",
    "Reiniciar": "Restart",
    "Detener": "Stop",
    "Iniciar": "Start",
    "Estado del Servicio": "Service Status",
    "Recargar Squid": "Reload Squid",
    "Reiniciar Squid": "Restart Squid",
    "Squid recargado": "Squid reloaded",
    "Squid reiniciado": "Squid restarted",
    "Recargando Squid...": "Reloading Squid...",
    "Reiniciando Squid...": "Restarting Squid...",
    "Reiniciar el servicio": "Restart the service",
    "Recarga la configuración de Squid sin reiniciar el servicio": "Reload Squid configuration without restarting the service",
    "Reinicia Squid y vuelve a aplicar la configuración desde cero": "Restart Squid and reapply configuration from scratch",
    "Resetear conexiones": "Reset connections",
    "Esta variable está protegida y no puede ser modificada desde aquí": "This variable is protected and cannot be modified from here",
    "Deshabilitado por errores de configuración": "Disabled due to configuration errors",
    "Directorio:": "Directory:",
    "Directorio de Salvas": "Backup Directory",
    "Directorio de salida": "Output directory",
    "Dir. Remota": "Remote Dir.",
    # ── Errors & Success ──
    "Error": "Error",
    "Éxito": "Success",
    "Éxitos": "Successes",
    "Advertencia": "Warning",
    "Advertencias": "Warnings",
    "Información": "Information",
    "Error interno del servidor": "Internal server error",
    "Error interno al cambiar estado de blocklist": "Internal error changing blocklist status",
    "Error interno al obtener los archivos": "Internal error getting files",
    "Error interno ejecutando la auditoría": "Internal error running audit",
    "Archivo no encontrado": "File not found",
    "Acceso denegado": "Access denied",
    "No autorizado": "Unauthorized",
    "Operación exitosa": "Operation successful",
    "Operación completada": "Operation completed",
    "Operación cancelada": "Operation cancelled",
    "Datos inválidos": "Invalid data",
    "Campo requerido": "Required field",
    "Formato inválido": "Invalid format",
    "Error de conexión": "Connection error",
    "Error de autenticación": "Authentication error",
    "Sesión expirada": "Session expired",
    "Usuario no encontrado": "User not found",
    "Usuario no encontrado.": "User not found.",
    "Error al cargar": "Error loading",
    "Error al eliminar": "Error deleting",
    "Error al guardar": "Error saving",
    "Error al cargar los datos": "Error loading data",
    "Error en la actualización": "Error during update",
    "Error en la operación": "Error in operation",
    "Eliminado correctamente": "Deleted successfully",
    "Guardado correctamente": "Saved successfully",
    "Actualizando...": "Updating...",
    "Actualización completada": "Update completed",
    "Respaldo creado": "Backup created",
    "Respaldo eliminado": "Backup deleted",
    "Restaurando respaldo...": "Restoring backup...",
    "Creando respaldo...": "Creating backup...",
    "Datos de la tabla eliminados correctamente": "Table data deleted successfully",
    "JSON inválido": "Invalid JSON",
    "Tipo de auditoría inválido": "Invalid audit type",
    "Selecciona un delay pool válido": "Select a valid delay pool",
    "Error:": "Error:",
    "Internal error": "Internal error",
    "Error DNS": "DNS Error",
    "Error Parsing": "Parsing Error",
    # ── Squid specific ──
    "Actualizar paquetes y configuración de Squid": "Update Squid packages and configuration",
    "Actualizar aplicación web SquidStats": "Update SquidStats web application",
    "Squid": "Squid",
    "SquidStats": "SquidStats",
    "Web": "Web",
    "Caché": "Cache",
    "Proxy": "Proxy",
    "SquidStats Monitor": "SquidStats Monitor",
    # ── Error page ──
    "Error - Squid Monitor": "Error - Squid Monitor",
    "Volver al Inicio": "Back to Home",
    "Volver al Dashboard Principal": "Back to Main Dashboard",
    "Disculpamos las molestias. Por favor, intenta de nuevo más tarde o contacta al soporte si el problema persiste.": "We apologize for the inconvenience. Please try again later or contact support if the problem persists.",
    # ── Notifications ──
    "Cargando notificaciones...": "Loading notifications...",
    "Ver todas las notificaciones": "View all notifications",
    "Todas las Notificaciones": "All Notifications",
    "No hay notificaciones": "No notifications",
    "Marcar todo como leído": "Mark all as read",
    "Marcar como leída": "Mark as read",
    "Marcar todas como leídas": "Mark all as read",
    "Marcar todas": "Mark all",
    "Eliminar notificación": "Delete notification",
    "Eliminar todas": "Delete all",
    "Leer": "Read",
    "No leído": "Unread",
    "Leída": "Read",
    "No leída": "Unread",
    "No leídas": "Unread",
    "Sin leer": "Unread",
    "Logo SquidStats": "SquidStats Logo",
    "Toggle menu": "Toggle menu",
    "Reciente": "Recent",
    "Todos los estados": "All statuses",
    "Todos los tipos": "All types",
    # ── LDAP ──
    "Configuración LDAP": "LDAP Configuration",
    "LDAP / Active Directory": "LDAP / Active Directory",
    "LDAP / Active Directory | Admin Squid": "LDAP / Active Directory | Squid Admin",
    "Configuración LDAP guardada.": "LDAP configuration saved.",
    "Error al guardar la configuración.": "Error saving configuration.",
    "No se ha configurado el servidor LDAP.": "LDAP server has not been configured.",
    "Error interno al probar LDAP.": "Internal error testing LDAP.",
    "LDAP no configurado.": "LDAP not configured.",
    "Parámetro 'q' requerido.": "Parameter 'q' required.",
    "Parámetro 'username' requerido.": "Parameter 'username' required.",
    "Conexión exitosa al servidor LDAP/AD.": "Successfully connected to LDAP/AD server.",
    "Probar Conexión": "Test Connection",
    "Servidor (host)": "Server (host)",
    "Base DN": "Base DN",
    "Bind DN / Usuario": "Bind DN / User",
    "Usar SSL / LDAPS": "Use SSL / LDAPS",
    "Buscar Usuarios": "Search Users",
    "Buscar Grupos": "Search Groups",
    "Ver grupos del usuario": "View user groups",
    "Ver grupos": "View groups",
    "Configura la conexión y explora el directorio.": "Configure the connection and explore the directory.",
    # ── Backup ──
    "Motor de BD desconocido": "Unknown database engine",
    "Frecuencia inválida": "Invalid frequency",
    "Configuración guardada correctamente": "Configuration saved successfully",
    "Error leyendo salvas": "Error reading backups",
    "Nombre de archivo inválido": "Invalid filename",
    "La salva no existe": "Backup does not exist",
    "Salvas de BD": "Database Backups",
    "Salvas de Base de Datos": "Database Backups",
    "Salvas automáticas": "Automatic Backups",
    "Sin salvas": "No backups",
    "No hay salvas disponibles": "No backups available",
    "Cargando salvas...": "Loading backups...",
    "Última Salva": "Last Backup",
    "Configura y gestiona las copias de seguridad automáticas": "Configure and manage automatic backups",
    "Realiza una salva manual o activa las automáticas": "Perform a manual backup or enable automatic backups",
    "Ruta absoluta donde se guardarán las salvas": "Absolute path where backups will be saved",
    "Máximo 3 salvas por período. Las más antiguas se eliminan automáticamente.": "Maximum 3 backups per period. Oldest ones are automatically deleted.",
    "Habilitar programación automática": "Enable automatic scheduling",
    "Retención máxima": "Maximum retention",
    "Fijo: 3 salvas": "Fixed: 3 backups",
    "Historial de Salvas": "Backup History",
    "Diaria — máx. 3 por mes": "Daily — max. 3 per month",
    "Diaria — máx. 3 por semana": "Daily — max. 3 per week",
    "¿Estás seguro de que deseas eliminar este respaldo?": "Are you sure you want to delete this backup?",
    # ── Database admin ──
    "Nombre de tabla no proporcionado": "Table name not provided",
    "Nombre de tabla inválido": "Invalid table name",
    "La tabla no existe": "Table does not exist",
    "No se puede eliminar estas tablas críticas": "Cannot delete these critical tables",
    "Limpiar Datos": "Clean Data",
    "Limpiar Datos - Administrador Squid Proxy": "Clean Data - Squid Proxy Administrator",
    "Eliminar Datos de Tabla": "Delete Table Data",
    "Selecciona una tabla y elimina todos sus datos": "Select a table and delete all its data",
    "Seleccionar Tabla": "Select Table",
    "Solo se eliminan los datos de la tabla, no la estructura": "Only table data is deleted, not the structure",
    "Se recomienda hacer un respaldo antes de eliminar datos importantes": "Making a backup before deleting important data is recommended",
    "Las tablas con sufijo de fecha (ej: log_20240121) son tablas diarias": "Tables with date suffix (e.g.: log_20240121) are daily tables",
    "Algunas tablas son críticas para el funcionamiento del sistema": "Some tables are critical for system operation",
    "Cargando tablas...": "Loading tables...",
    "Cargando información de la base de datos...": "Loading database information...",
    "Base de datos - Administrador Squid Proxy": "Database - Squid Proxy Administrator",
    "Motor de Base de Datos": "Database Engine",
    "Versión del Motor": "Engine Version",
    "Resumen DB": "DB Summary",
    "Detalles SQLite": "SQLite Details",
    "Tamaño de Página": "Page Size",
    "Páginas Totales": "Total Pages",
    "Páginas Libres": "Free Pages",
    "Tamaño Total": "Total Size",
    "Fragmentación": "Fragmentation",
    "Fragmentación:": "Fragmentation:",
    "Auto-Vacuum": "Auto-Vacuum",
    "Modo Journal": "Journal Mode",
    "Verificación de Integridad": "Integrity Check",
    "Detalle de Corrupción": "Corruption Detail",
    "La base de datos tiene páginas dañadas.": "The database has damaged pages.",
    "— considera ejecutar VACUUM": "— consider running VACUUM",
    "— dentro del rango normal": "— within normal range",
    "— ejecuta VACUUM urgentemente": "— run VACUUM urgently",
    "Esta operación puede tardar varios minutos en bases de datos grandes.": "This operation may take several minutes on large databases.",
    "Información de la Tabla": "Table Information",
    "Monitor de salud, copias de seguridad y gestión de datos": "Health monitoring, backups, and data management",
    # ── Split config ──
    "Archivo requerido no encontrado. Verifique la configuración del archivo squid.conf.": "Required file not found. Please check the squid.conf file configuration.",
    "No se tienen permisos suficientes para crear los archivos": "Insufficient permissions to create the files",
    "No se tienen permisos suficientes para leer los archivos": "Insufficient permissions to read the files",
    "Error de validación de la configuración": "Configuration validation error",
    "Error interno al dividir la configuración": "Internal error splitting configuration",
    "Archivo requerido no encontrado.": "Required file not found.",
    "Divide squid.conf en archivos modulares y crea respaldo": "Split squid.conf into modular files and create backup",
    "Archivo de entrada": "Input file",
    "Archivos Generados": "Generated Files",
    "Archivos que se generarán": "Files that will be generated",
    "Ver Archivos Generados": "View Generated Files",
    "archivos generados": "generated files",
    "Abre un modal con los archivos generados por la división": "Opens a modal with the files generated by the split",
    "No dividido aún": "Not split yet",
    "No se encontraron configuraciones": "No configurations found",
    "Modo estricto": "Strict mode",
    "Abortar si se encuentran directivas desconocidas": "Abort if unknown directives are found",
    "Esta herramienta divide tu archivo monolítico": "This tool splits your monolithic file",
    "en múltiples archivos modulares organizados por categorías. Esto facilita:": "into multiple modular files organized by categories. This facilitates:",
    "Mejor organización de directivas por funcionalidad": "Better organization of directives by functionality",
    "Facilita la edición desde la interfaz web": "Makes editing from the web interface easier",
    "Reduce errores al editar configuraciones complejas": "Reduces errors when editing complex configurations",
    "Gestión y mantenimiento más sencillo de la configuración": "Easier configuration management and maintenance",
    "Esta operación creará múltiples archivos en el directorio": "This operation will create multiple files in the directory",
    "para una mejor gestión modular.": "for better modular management.",
    "¿Tu configuración ya está dividida en módulos?": "Is your configuration already split into modules?",
    "dividir tu configuración": "split your configuration",
    "Si tu squid.conf aún no está dividido, puedes": "If your squid.conf is not split yet, you can",
    # ── Quota ──
    "Cuota": "Quota",
    "Cuota (MB)": "Quota (MB)",
    "Cuota excedida": "Quota exceeded",
    "Cuota restante": "Remaining quota",
    "Cuota global con el usuario": "Global quota with user",
    "Cuotas de Usuario(Mensual) - Administración Squid": "User Quotas (Monthly) - Squid Administration",
    "Cuotas por Grupo": "Quotas by Group",
    "Cuotas por Usuario": "Quotas by User",
    "Datos consumidos (MB):": "Data consumed (MB):",
    "Datos totales (GB):": "Total data (GB):",
    "Datos extraídos del archivo de bloqueos de quota.": "Data extracted from quota block file.",
    "Consumo total": "Total consumption",
    "Uso (MB)": "Usage (MB)",
    "Usado (MB)": "Used (MB)",
    "Datos (MB)": "Data (MB)",
    "Datos Transmitidos": "Transmitted Data",
    "Resumen de Cuotas": "Quota Summary",
    "Editar cuota": "Edit quota",
    "Guardar Cuota": "Save Quota",
    "Guardar Grupo": "Save Group",
    "Total de Datos Consumidos": "Total Consumed Data",
    "Total de datos transferidos": "Total transferred data",
    "Histórico de Eventos de Cuotas": "Quota Event History",
    "Revisa las acciones registradas cuando usuarios superaron sus límites.": "Review registered actions when users exceeded their limits.",
    "Define límites grupales para los usuarios conectados al proxy.": "Define group limits for users connected to the proxy.",
    "Configura y revisa cuotas específicas por usuario de Squid.": "Configure and review specific quotas per Squid user.",
    "Activa o desactiva el control de cuotas para usuarios y grupos": "Enable or disable quota control for users and groups",
    "Incidentes de exceso": "Excess incidents",
    "No hay usuarios con cuota configurada": "No users with quota configured",
    "No hay grupos con cuota configurada": "No groups with quota configured",
    "Grupos con cuota": "Groups with quota",
    "Política de excedente": "Excess policy",
    "Límite": "Limit",
    "Consumido": "Consumed",
    "Restante": "Remaining",
    "límite global": "global limit",
    "todos los usuarios que no tengan una cuota individual": "all users without an individual quota",
    "usuarios en esta página.": "users on this page.",
    "y le asignas una cuota, esa cuota actuará como": "and assign a quota to it, that quota will act as a",
    "y le asignas una cuota, ese límite se aplicará automáticamente a": "and assign a quota to it, that limit will automatically apply to",
    "Este usuario no pertenece a ningún grupo.": "This user does not belong to any group.",
    "Información sobre el usuario default": "Information about the default user",
    "Información sobre la política por defecto": "Information about the default policy",
    "Para ver los delay pools debes iniciar sesión.": "You must log in to view delay pools.",
    "Total de velocidad del usuario": "Total user speed",
    # ── ACLs ──
    "ACL actualizada": "ACL updated",
    "ACL agregada": "ACL added",
    "ACL eliminada": "ACL deleted",
    "Gestión de ACLs": "ACL Management",
    "Gestión de Access Control Lists (ACLs)": "Access Control Lists (ACLs) Management",
    "Agregar ACL": "Add ACL",
    "Agregar Nueva ACL": "Add New ACL",
    "Crear ACL": "Create ACL",
    "Editar ACL": "Edit ACL",
    "Guardar ACL": "Save ACL",
    "Total ACLs": "Total ACLs",
    "Actualizar ACL": "Update ACL",
    "Crear primera ACL": "Create first ACL",
    "No hay ACLs configuradas": "No ACLs configured",
    "No hay ACLs personalizadas configuradas": "No custom ACLs configured",
    "¿Ya tienes ACLs configuradas?": "Do you already have ACLs configured?",
    "Las ACLs predefinidas de Squid siguen disponibles": "Squid predefined ACLs remain available",
    "Las ACLs son fundamentales para controlar el acceso en Squid": "ACLs are fundamental for controlling access in Squid",
    "Usa las ACLs en reglas de http_access, http_reply_access, etc.": "Use ACLs in http_access, http_reply_access rules, etc.",
    "Haz clic en estas ACLs predefinidas para agregarlas rápidamente": "Click these predefined ACLs to quickly add them",
    "Nombre de la ACL:": "ACL name:",
    "Tipo de ACL:": "ACL type:",
    "Descripción de esta ACL": "Description for this ACL",
    "El tipo no se puede cambiar, crea una nueva ACL si necesitas otro tipo": "The type cannot be changed, create a new ACL if you need a different type",
    "Selecciona un tipo...": "Select a type...",
    "ACLs:": "ACLs:",
    "ACLs Comunes (opcional):": "Common ACLs (optional):",
    "ACLs predefinidas:": "Predefined ACLs:",
    "ACLs lentas - pueden requerir DNS o autenticación": "Slow ACLs - may require DNS or authentication",
    "ACLs rápidas - no requieren lookups externos": "Fast ACLs - no external lookups required",
    "Acerca de las ACLs:": "About ACLs:",
    "Define condiciones para controlar el acceso al proxy": "Define conditions to control proxy access",
    "Descripción (opcional):": "Description (optional):",
    "Comentario (opcional):": "Comment (optional):",
    "Opciones (opcional):": "Options (optional):",
    "Opciones:": "Options:",
    "Agregar valor": "Add value",
    "Se agregará como comentario antes de la ACL": "Will be added as a comment before the ACL",
    "Solo letras, números, guiones y guiones bajos": "Only letters, numbers, hyphens and underscores",
    "Contiene negación (!) - se aplica cuando NO coincide con la ACL": "Contains negation (!) - applies when NOT matching the ACL",
    "antes del nombre de una ACL para negación. Ej:": "before ACL name for negation. E.g.:",
    # ── HTTP Access ──
    "HTTP Access": "HTTP Access",
    "Reglas HTTP": "HTTP Rules",
    "Reglas de Acceso HTTP": "HTTP Access Rules",
    "Reglas de Acceso (ACLs):": "Access Rules (ACLs):",
    "Reglas de Acceso:": "Access Rules:",
    "Reglas de Control": "Control Rules",
    "Reglas": "Rules",
    "Agregar Regla": "Add Rule",
    "Agregar Regla HTTP Access": "Add HTTP Access Rule",
    "Agregar regla de acceso": "Add access rule",
    "Crear Regla": "Create Rule",
    "Guardar Regla": "Save Rule",
    "Editar Regla HTTP Access": "Edit HTTP Access Rule",
    "Crear nueva regla de acceso": "Create new access rule",
    "Crear nueva regla de acceso (deshabilitado)": "Create new access rule (disabled)",
    "Crear primera regla": "Create first rule",
    "No hay reglas HTTP access configuradas": "No HTTP access rules configured",
    "¿Ya tienes reglas configuradas?": "Do you already have rules configured?",
    "Regla activa:": "Active rule:",
    "Permitir acceso": "Allow access",
    "Denegar acceso": "Deny access",
    "La primera regla que coincida se aplica (allow o deny)": "The first matching rule applies (allow or deny)",
    "Las reglas se procesan de arriba hacia abajo": "Rules are processed from top to bottom",
    'Se recomienda terminar con \\"deny all\\" para evitar confusión': 'It is recommended to end with \\"deny all\\" to avoid confusion',
    "Se agregará como comentario antes de la regla": "Will be added as a comment before the rule",
    "Importante sobre el orden:": "Important about order:",
    "Mover arriba": "Move up",
    "Mover abajo": "Move down",
    "⚠️ Sin reglas, el acceso será DENEGADO por defecto": "⚠️ Without rules, access will be DENIED by default",
    "🔒 Política por defecto:": "🔒 Default policy:",
    "http_access deny": "http_access deny",
    # ── Delay Pools ──
    "Gestión de Delay Pools": "Delay Pool Management",
    "¿Qué son los Delay Pools?": "What are Delay Pools?",
    "Delay Pool": "Delay Pool",
    "Agregar Nuevo Delay Pool": "Add New Delay Pool",
    "Agregar Pool": "Add Pool",
    "Crear Pool": "Create Pool",
    "Crear primer Pool": "Create first Pool",
    "Editar Delay Pool": "Edit Delay Pool",
    "No hay delay pools configurados": "No delay pools configured",
    "¿Ya tienes delay pools configurados?": "Do you already have delay pools configured?",
    "Pools configurados": "Configured pools",
    "Número de Pool:": "Pool number:",
    "Número único del pool (1-255)": "Unique pool number (1-255)",
    "Clase de Pool:": "Pool class:",
    "Seleccione una clase...": "Select a class...",
    "Velocidad Individual": "Individual Speed",
    "Velocidad Agregada": "Aggregate Speed",
    "Red Asociada": "Associated Network",
    "Parámetros de Velocidad:": "Speed Parameters:",
    "Parámetros:": "Parameters:",
    "Formato: restore/max (bytes por segundo)": "Format: restore/max (bytes per second)",
    "Formato: restore/max (bytes/seg)": "Format: restore/max (bytes/sec)",
    "Individual por host (restore/max):": "Individual per host (restore/max):",
    "Individual (por host):": "Individual (per host):",
    "Agregado (restore/max en bytes/seg):": "Aggregate (restore/max in bytes/sec):",
    "Agregado (restore/max):": "Aggregate (restore/max):",
    "Agregado:": "Aggregate:",
    "Por red (restore/max):": "Per network (restore/max):",
    "Parámetros por tag (restore/max):": "Parameters per tag (restore/max):",
    "Red:": "Network:",
    "Clases disponibles:": "Available classes:",
    "Clase 1 - Bucket único agregado": "Class 1 - Single aggregate bucket",
    "Clase 1:": "Class 1:",
    "Clase 2 - Agregado + por host (/24)": "Class 2 - Aggregate + per host (/24)",
    "Clase 2:": "Class 2:",
    "Clase 3 - Agregado + red + por host (/16)": "Class 3 - Aggregate + network + per host (/16)",
    "Clase 3:": "Class 3:",
    "Clase 4 - Como clase 3 + por usuario": "Class 4 - Like class 3 + per user",
    "Clase 4:": "Class 4:",
    "Clase 5 - Basado en tags": "Class 5 - Tag-based",
    "Clase 5:": "Class 5:",
    "Bucket único agregado para todos los clientes": "Single aggregate bucket for all clients",
    "Un solo bucket agregado para todos los clientes": "A single aggregate bucket for all clients",
    "Bucket agregado + 255 buckets individuales por host": "Aggregate bucket + 255 individual buckets per host",
    "Bucket agregado + 255 buckets por host (red /24)": "Aggregate bucket + 255 buckets per host (/24 network)",
    "Bucket agregado + buckets individuales por host (/24)": "Aggregate bucket + individual buckets per host (/24)",
    "Buckets basados en tags de external_acl_type": "Buckets based on external_acl_type tags",
    "Basado en tags de external_acl_type": "Based on external_acl_type tags",
    "Basado en tags de external_acl_type (un bucket por tag)": "Based on external_acl_type tags (one bucket per tag)",
    "Como clase 3 + buckets por usuario autenticado": "Like class 3 + buckets per authenticated user",
    "Buckets por subred + buckets individuales por host (/16)": "Buckets per subnet + individual buckets per host (/16)",
    "Buckets por subred + buckets por host (red /16)": "Buckets per subnet + buckets per host (/16 network)",
    "Buckets por subred + por host": "Buckets per subnet + per host",
    "Una conexión puede tomar todo el ancho de banda de un bucket": "One connection can take all the bandwidth of a bucket",
    "No limita overheads como TCP, ICP, DNS, etc.": "Does not limit overheads like TCP, ICP, DNS, etc.",
    "Limitaciones importantes:": "Important limitations:",
    "Usa -1/-1 para deshabilitar": "Use -1/-1 to disable",
    "Usa -1/-1 para deshabilitar este bucket": "Use -1/-1 to disable this bucket",
    "Selecciona el delay pool": "Select the delay pool",
    "Asigna la IP del usuario a un": "Assign the user's IP to a",
    "delay pool": "delay pool",
    "Degradar velocidad (próximamente)": "Throttle speed (coming soon)",
    "Solo notificar (próximamente)": "Notify only (coming soon)",
    # ── Users ──
    "Nombre, usuario, email…": "Name, user, email...",
    "Complete el formulario para crear un nuevo usuario administrador.": "Complete the form to create a new administrator user.",
    "Modifique los datos del usuario según sea necesario.": "Modify user data as needed.",
    "Usuario/Grupo": "User/Group",
    "Nombre de grupo": "Group name",
    "Nombre del grupo": "Group name",
    "Nombre del grupo…": "Group name...",
    "Nombre del Host": "Host Name",
    "Grupo (opcional)": "Group (optional)",
    "Grupos de": "Groups of",
    "Miembros": "Members",
    "Bloquear usuario": "Block user",
    "Desbloquear usuario": "Unblock user",
    "Reducir velocidad": "Reduce speed",
    "Restaurar velocidad": "Restore speed",
    "Confirmar bloqueo": "Confirm block",
    "¿Estás seguro de que deseas bloquear a este usuario?": "Are you sure you want to block this user?",
    "¿Estás seguro de que deseas desbloquear a este usuario?": "Are you sure you want to unblock this user?",
    "¿Estás seguro de que deseas reducir la velocidad de este usuario?": "Are you sure you want to reduce this user's speed?",
    "¿Estás seguro de que deseas restaurar la velocidad de este usuario?": "Are you sure you want to restore this user's speed?",
    "Buscar por usuario...": "Search by user...",
    "Buscar usuario...": "Search user...",
    "Filtrar por usuario": "Filter by user",
    "Filtrar por fecha": "Filter by date",
    "Filtrar por:": "Filter by:",
    "Resumen de Usuario": "User Summary",
    "Resumen por Usuario": "Summary by User",
    "Actividad del usuario": "User activity",
    "Actividad y logs de usuarios": "User activity and logs",
    "Ver y filtrar en tiempo real por nombre de usuario.": "View and filter in real time by username.",
    "Búsqueda por Palabra Clave": "Keyword Search",
    "Palabra Clave": "Keyword",
    "Por Usuario": "By User",
    "Por Grupo": "By Group",
    "Pool #": "Pool #",
    # ── Audit ──
    "Auditoría del Sistema": "System Audit",
    "Auditoría -": "Audit -",
    "Auditoría de actividad por usuario y fecha": "Activity audit by user and date",
    "Auditoría:": "Audit:",
    "Tipo de Auditoría": "Audit Type",
    "Evento": "Event",
    "Acción": "Action",
    "Acción:": "Action:",
    "Objeto": "Object",
    "Cambios": "Changes",
    "Antes": "Before",
    "Después": "After",
    "Sin cambios": "No changes",
    "Buscar auditoría": "Search audit",
    "Histórico": "History",
    "Los resultados de su auditoría aparecerán aquí.": "Your audit results will appear here.",
    # ── Stats ──
    "Actividad Diaria": "Daily Activity",
    "Actividad diaria": "Daily activity",
    "Actividad por Dirección IP": "Activity by IP Address",
    "Actividad en Redes Sociales": "Social Media Activity",
    "Redes Sociales": "Social Media",
    "Ancho de Banda": "Bandwidth",
    "Ancho de banda total": "Total bandwidth",
    "Velocidad": "Speed",
    "Conexiones": "Connections",
    "Solicitudes": "Requests",
    "Respuestas": "Responses",
    "Errores": "Errors",
    "Aciertos": "Hits",
    "Fallos": "Misses",
    "Aciertos de caché": "Cache hits",
    "Fallos de caché": "Cache misses",
    "Tasa de aciertos": "Hit rate",
    "Porcentaje": "Percentage",
    "Gráfico": "Chart",
    "Lista": "List",
    "Visitas": "Visits",
    "Visitas Únicas": "Unique Visits",
    "Número de Visitas": "Number of Visits",
    "Peticiones": "Requests",
    "Peticiones HTTP": "HTTP Requests",
    "Peticiones/Min": "Requests/Min",
    "Total peticiones:": "Total requests:",
    "Total solicitudes:": "Total requests:",
    "Total usuarios:": "Total users:",
    "Total de solicitudes": "Total requests",
    "Total Bandwidth": "Total Bandwidth",
    "Total Requests": "Total Requests",
    "Bytes enviados": "Bytes sent",
    "Bytes recibidos": "Bytes received",
    "Distribución de Códigos HTTP": "HTTP Code Distribution",
    "Distribución de códigos HTTP": "HTTP code distribution",
    "Análisis por Código de Respuesta": "Response Code Analysis",
    "Análisis parcial — límite de dominios activo": "Partial analysis — domain limit active",
    "Código HTTP": "HTTP Code",
    "Resumen de respuestas": "Response summary",
    "Resumen General": "General Summary",
    "IPs Compartidas por Múltiples Usuarios": "IPs Shared by Multiple Users",
    "Direcciones IP": "IP Addresses",
    "No hay conexiones activas": "No active connections",
    "No se encontraron datos": "No data found",
    "No se encontraron registros": "No records found",
    "No hay registros disponibles": "No records available",
    "No hay actividad en sitios bloqueados para mostrar.": "No activity on blocked sites to show.",
    "Top 10 IPs (Datos)": "Top 10 IPs (Data)",
    "Top 10 Usuarios (Datos)": "Top 10 Users (Data)",
    "Top 10 Usuarios (Peticiones)": "Top 10 Users (Requests)",
    "Top 15 URLs (Datos)": "Top 15 URLs (Data)",
    "Top 20 Páginas Más Visitadas": "Top 20 Most Visited Pages",
    "Top 20 Usuarios por Actividad": "Top 20 Users by Activity",
    "Top 20 Usuarios por Datos Transmitidos": "Top 20 Users by Transmitted Data",
    "Top IPs por datos": "Top IPs by data",
    "Top URLs por consumo de datos": "Top URLs by data consumption",
    "Top URLs por datos": "Top URLs by data",
    "Top dominios": "Top domains",
    "Top usuarios por actividad": "Top users by activity",
    "Top usuarios por datos": "Top users by data",
    "Top usuarios por solicitudes": "Top users by requests",
    # ── Common phrases ──
    "Guardar cambios": "Save changes",
    "Guardar Cambios": "Save Changes",
    "Descartar cambios": "Discard changes",
    "¿Estás seguro?": "Are you sure?",
    "Esta acción no se puede deshacer": "This action cannot be undone",
    "Esta acción no se puede deshacer.": "This action cannot be undone.",
    "Confirmar eliminación": "Confirm deletion",
    "Confirmar acción": "Confirm action",
    "¿Estás seguro de que deseas eliminar esto?": "Are you sure you want to delete this?",
    "Seleccionar todo": "Select all",
    "Deseleccionar todo": "Deselect all",
    "Sin resultados": "No results",
    "Mostrando": "Showing",
    "de": "of",
    "resultados": "results",
    "registros": "records",
    "por página": "per page",
    "Página": "Page",
    "Columna": "Column",
    "Valor": "Value",
    "Fecha y Hora": "Date and Time",
    "Tráfico": "Traffic",
    "Información": "Information",
    "Aviso": "Notice",
    "Atención": "Attention",
    "Importante": "Important",
    "Nota": "Note",
    "Versión": "Version",
    "Licencia": "License",
    "Documentación": "Documentation",
    "Soporte": "Support",
    "Ayuda": "Help",
    "Acerca de": "About",
    "Acciones Rápidas": "Quick Actions",
    "Información general": "General information",
    "Información Importante": "Important Information",
    "Funcionalidad en Beta": "Functionality in Beta",
    "Personalizada": "Custom",
    "Selección múltiple": "Multiple selection",
    "Seleccione una opción": "Select an option",
    "Requerido": "Required",
    "Opcional": "Optional",
    "Ejemplo:": "Example:",
    "Nombre:": "Name:",
    "Tipo:": "Type:",
    "Valores:": "Values:",
    "Limpiar búsqueda": "Clear search",
    "Limpiar filtros": "Clear filters",
    "Reintentar": "Retry",
    "Rechazado": "Rejected",
    "Proxies:": "Proxies:",
    "grupo(s) encontrado(s)": "group(s) found",
    "líneas": "lines",
    "núcleos": "cores",
    "Generado:": "Generated:",
    "- Generado:": "- Generated:",
    "operando con normalidad": "operating normally",
    "Ver Resumen": "View Summary",
    "o restaura desde una copia sana.": "or restore from a healthy copy.",
    "Haz un respaldo y ejecuta": "Make a backup and run",
    "No se encontraron grupos.": "No groups found.",
    "No se encontraron usuarios.": "No users found.",
    "No se encontraron bloqueos (archivo vacío o no existe).": "No blocks found (file empty or does not exist).",
    # ── Misc UI ──
    "¿Deseas actualizar Squid?": "Do you want to update Squid?",
    "¿Deseas actualizar SquidStats?": "Do you want to update SquidStats?",
    "¡Advertencia!": "Warning!",
    "¡MUY IMPORTANTE!": "VERY IMPORTANT!",
    "¿Qué hace esta funcionalidad?": "What does this functionality do?",
    "(Próx.)": "(Next)",
    "(dejar vacío para mantener la actual)": "(leave empty to keep current)",
    "-- Seleccione un código --": "-- Select a code --",
    "-- Todos --": "-- All --",
    "| Filtros:": "| Filters:",
    "💡 Usuario": "💡 User",
    "Intervalo de refresco (segundos)": "Refresh interval (seconds)",
    "Token (opcional)": "Token (optional)",
    "Timeout": "Timeout",
    "Tip:": "Tip:",
    "Usa": "Use",
    "API Token": "API Token",
    "Si creas un usuario con el nombre": "If you create a user with the name",
    "Si creas un usuario llamado": "If you create a user named",
    "Alternador n.º de línea": "Toggle line number",
    "Alternar n.º de línea": "Toggle line number",
    "Modulariza tu archivo squid.conf para una gestión más sencilla": "Modularize your squid.conf for easier management",
    "Información del Sistema": "System Information",
    "Procesador": "Processor",
    "Memoria RAM": "RAM",
    "Almacenamiento": "Storage",
    "Red": "Network",
    "Interfaz": "Interface",
    "Dirección": "Address",
    "Cargando pools...": "Loading pools...",
    "Cargando grupos…": "Loading groups...",
    "Esta funcionalidad se encuentra en": "This functionality is in",
    "Lista membership": "List membership",
    "N/A": "N/A",
    "Esta acción bloqueará todo el tráfico del usuario. Se añadirá": "This action will block all user traffic. It will be added",
    "En Squid": "In Squid",
    "Activa en Squid": "Active in Squid",
    "instalado en el servidor.": "installed on the server.",
    "en Squid y se guardará en la base de datos para persistencia.": "in Squid and will be saved in the database for persistence.",
    # ── Social media ──
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "Twitter/X": "Twitter/X",
    "WhatsApp": "WhatsApp",
    "YouTube": "YouTube",
    "Pinterest": "Pinterest",
    "Telegram": "Telegram",
    # ── Squid config technical ──
    "Kbps": "Kbps",
    "Mbps": "Mbps",
    "Gbps": "Gbps",
    "MB": "MB",
    "GB": "GB",
    "SWAP": "SWAP",
    "RAM": "RAM",
    "CPU": "CPU",
    "RC": "RC",
    "VACUUM": "VACUUM",
    "SSL Bump": "SSL Bump",
    "SSL Bump (MITM)": "SSL Bump (MITM)",
    "BETA": "BETA",
    "Beta": "Beta",
    "PDF": "PDF",
    "Git": "Git",
    "ALLOW": "ALLOW",
    "DENY": "DENY",
    "BUILT-IN": "BUILT-IN",
    "DNSmasq": "DNSmasq",
    "Pi-hole": "Pi-hole",
    "AdGuard": "AdGuard",
    "MySQL / MariaDB": "MySQL / MariaDB",
    "PostgreSQL": "PostgreSQL",
    "SQLite": "SQLite",
    "NTLM (AD)": "NTLM (AD)",
    "SIMPLE (LDAP)": "SIMPLE (LDAP)",
    "CONNECT": "CONNECT",
    "SquidStats logo": "SquidStats logo",
    "SquidStats v": "SquidStats v",
    "Case-insensitive": "Case-insensitive",
    "No lookups": "No lookups",
    "Requests": "Requests",
    "No valid domains specified for search.": "No valid domains specified for search.",
    "Error al detectar la configuración SSL Bump": "Error detecting SSL Bump configuration",
    "Error al ejecutar la verificación": "Error running verification",
    # ── Examples & placeholders ──
    "192.168.1.2 or example.com": "192.168.1.2 or example.com",
    "CN=admin,DC=empresa,DC=com": "CN=admin,DC=company,DC=com",
    "DC=empresa,DC=com": "DC=company,DC=com",
    "Ej. 10240": "E.g. 10240",
    "Ej. 2048": "E.g. 2048",
    "Ej: 192.168.1.100": "E.g.: 192.168.1.100",
    "Ej: 64000/64000 = 512 Kbps": "E.g.: 64000/64000 = 512 Kbps",
    "Ej: Permitir acceso desde la red local": "E.g.: Allow access from local network",
    "Ej: juegos, descargas...": "E.g.: games, downloads...",
    # ── Remaining ACL type descriptions ──
    "src (IP origen)": "src (Source IP)",
    "dst (IP destino)": "dst (Destination IP)",
    "dstdomain (Dominio destino)": "dstdomain (Destination domain)",
    "port (Puerto)": "port (Port)",
    "time (Tiempo)": "time (Time)",
    "method (Método HTTP)": "method (HTTP Method)",
    "proxy_auth (Autenticación)": "proxy_auth (Authentication)",
    "maxconn (Conexiones máximas)": "maxconn (Maximum connections)",
    "src - IP origen del cliente": "src - Client source IP",
    "dst - IP destino [slow]": "dst - Destination IP [slow]",
    "localip - IP local de conexión": "localip - Local connection IP",
    "src_as - AS number origen": "src_as - Source AS number",
    "dst_as - AS number destino": "dst_as - Destination AS number",
    "dstdomain - Dominio destino": "dstdomain - Destination domain",
    "srcdomain - Dominio origen [slow]": "srcdomain - Source domain [slow]",
    "dstdom_regex - Regex dominio destino": "dstdom_regex - Destination domain regex",
    "srcdom_regex - Regex dominio origen [slow]": "srcdom_regex - Source domain regex [slow]",
    "port - Puerto TCP destino": "port - Destination TCP port",
    "localport - Puerto local": "localport - Local port",
    "myportname - Nombre de puerto": "myportname - Port name",
    "time - Día y hora": "time - Day and time",
    "url_regex - Regex en URL completa": "url_regex - Full URL regex",
    "urlpath_regex - Regex en path": "urlpath_regex - Path regex",
    "urllogin - Regex en login URL": "urllogin - Login URL regex",
    "proto - Protocolo (HTTP/FTP)": "proto - Protocol (HTTP/FTP)",
    "method - Método HTTP": "method - HTTP Method",
    "http_status - Código HTTP": "http_status - HTTP Code",
    "proxy_auth - Usuario proxy [slow]": "proxy_auth - Proxy user [slow]",
    "proxy_auth_regex - Regex usuario [slow]": "proxy_auth_regex - User regex [slow]",
    "ext_user - Usuario externo [slow]": "ext_user - External user [slow]",
    "ext_user_regex - Regex usuario ext [slow]": "ext_user_regex - External user regex [slow]",
    "browser - User-Agent": "browser - User-Agent",
    "referer_regex - Referer": "referer_regex - Referer",
    "req_mime_type - MIME request": "req_mime_type - MIME request",
    "rep_mime_type - MIME reply": "rep_mime_type - MIME reply",
    "req_header - Header request": "req_header - Header request",
    "rep_header - Header reply": "rep_header - Header reply",
    "ssl_error - Error SSL": "ssl_error - SSL Error",
    "server_cert_fingerprint - Fingerprint": "server_cert_fingerprint - Fingerprint",
    "ssl::server_name - SNI": "ssl::server_name - SNI",
    "ssl::server_name_regex - SNI regex": "ssl::server_name_regex - SNI regex",
    "maxconn - Max conexiones IP": "maxconn - Max IP connections",
    "max_user_ip - Max IPs usuario": "max_user_ip - Max user IPs",
    "external - Helper externo [slow]": "external - External helper [slow]",
    "random - Probabilidad random": "random - Random probability",
    "note - Anotación transacción": "note - Transaction annotation",
    "any-of - Grupo OR": "any-of - OR Group",
    "all-of - Grupo AND": "all-of - AND Group",
    # ── Remaining long Spanish phrases ──
    "Todas las notificaciones aparecerán aquí. ¡Mantente atento a las actualizaciones del sistema!": "All notifications will appear here. Stay tuned for system updates!",
    "Si ya está dividido, verifica que los archivos estén en el directorio correcto o edítalos directamente desde": "If already split, verify files are in the correct directory or edit them directly from",
    "Por favor, no la uses en producción de momento. Úsala únicamente en un entorno de prueba.": "Please do not use it in production yet. Use it only in a testing environment.",
    "Conecta y sincroniza listas bloqueadas desde un servidor Pi-hole. Aquí puedes configurar conexión y ver el estado.": "Connect and sync blocked lists from a Pi-hole server. Here you can configure the connection and check the status.",
    "Esta acción es irreversible. Una vez eliminados los datos, no se pueden recuperar.": "This action is irreversible. Once data is deleted, it cannot be recovered.",
    "No se han detectado ACLs, reglas HTTP ni delay pools en tu configuración de Squid.": "No ACLs, HTTP rules, or delay pools were detected in your Squid configuration.",
    "Si ya tienes tu configuración organizada en archivos separados (por ejemplo: acls.conf, http_access.conf, delay_pools.conf), SquidStats puede leerla directamente sin necesidad de unificarla.": "If you already have your configuration organized in separate files (e.g.: acls.conf, http_access.conf, delay_pools.conf), SquidStats can read it directly without needing to unify it.",
    "Verifica la integridad estructural de la base de datos en busca de posibles errores o corrupción.": "Verify the structural integrity of the database looking for possible errors or corruption.",
    "Se mantienen las 3 salvas más recientes. Las más antiguas se eliminan automáticamente.": "The 3 most recent backups are kept. Oldest ones are automatically deleted.",
    "Los delay pools permiten limitar el ancho de banda de ciertas solicitudes basadas en criterios específicos, proporcionando un control justo del tráfico.": "Delay pools allow limiting bandwidth for certain requests based on specific criteria, providing fair traffic control.",
    "Incompatible con slow aborts; usa quick abort bajo": "Incompatible with slow aborts; use quick abort under",
    "Las reglas se evalúan en orden. La primera coincidencia determina el acceso.": "Rules are evaluated in order. The first match determines access.",
    "Si ninguna regla coincide, se aplica el comportamiento contrario a la última regla": "If no rule matches, the opposite behavior of the last rule is applied",
    "coincide cuando NO es un puerto seguro.": "matches when it is NOT a safe port.",
    "líneas. Usa el filtro para encontrar rápidamente errores, IPs o partes del mensaje.": "lines. Use the filter to quickly find errors, IPs, or parts of the message.",
    "Visualiza el estado general de las cuotas de ancho de banda y límites de datos para los usuarios y grupos.": "View the general status of bandwidth quotas and data limits for users and groups.",
    "para todos los usuarios que no tengan una cuota individual configurada. La cuota individual siempre tiene prioridad sobre la global.": "for all users without an individual quota configured. Individual quota always has priority over the global one.",
    "Define el comportamiento al superar la cuota. (Por ejemplo: bloquear el acceso o degradar la velocidad).": "Define the behavior when exceeding the quota. (For example: block access or throttle speed).",
    "Aunque no haya ninguna regla guardada, el sistema aplica automáticamente la política de": "Even if no rule is saved, the system automatically applies the policy of",
    'cuando un usuario supera su cuota. Guarda explícitamente \\"Bloquear\\" si quieres que quede registrado.': 'when a user exceeds their quota. Explicitly save \\"Block\\" if you want it recorded.',
    "dominios activos. Para evitar un alto consumo de recursos, la consulta se ha limitado a los primeros": "active domains. To avoid high resource consumption, the query has been limited to the first",
    "dominios. Es posible que algunos accesos bloqueados no aparezcan en este listado.": "domains. Some blocked accesses may not appear in this list.",
    "Se eliminará el bloqueo activo para esta IP y se recargará la configuración de Squid.": "The active block for this IP will be removed and Squid configuration will be reloaded.",
    "existente. Sus conexiones estarán sujetas a los límites de ancho de banda configurados en ese pool.": "existing. Their connections will be subject to the bandwidth limits configured in that pool.",
    "Se eliminará la restricción de velocidad activa para esta IP y se recargará la configuración de Squid.": "The active speed restriction for this IP will be removed and Squid configuration will be reloaded.",
    "Requiere": "Requires",
    # ── Technical/pass-through strings ──
    "fa-times-circle": "fa-times-circle",
    "!Safe_ports": "!Safe_ports",
    "!SSL_ports": "!SSL_ports",
    "-i": "-i",
    "-n": "-n",
    "-m": "-m",
    "[fast]": "[fast]",
    "[slow]": "[slow]",
    "(dynamic)": "(dynamic)",
    "0 kbps": "0 kbps",
    "0 B": "0 B",
    "0G": "0G",
    "cert:": "cert:",
    "all, manager, localhost, to_localhost, to_linklocal, CONNECT": "all, manager, localhost, to_localhost, to_linklocal, CONNECT",
    "List membership": "List membership",
    "example.com\\nexample.org": "example.com\\nexample.org",
    # ── HTTP status codes ──
    "200 OK": "200 OK",
    "301 Moved Permanently": "301 Moved Permanently",
    "302 Found": "302 Found",
    "304 Not Modified": "304 Not Modified",
    "400 Bad Request": "400 Bad Request",
    "401 Unauthorized": "401 Unauthorized",
    "403 Forbidden": "403 Forbidden",
    "404 Not Found": "404 Not Found",
    "500 Internal Server Error": "500 Internal Server Error",
    "502 Bad Gateway": "502 Bad Gateway",
    "503 Service Unavailable": "503 Service Unavailable",
    "504 Gateway Timeout": "504 Gateway Timeout",
    # ── CSRF/validation ──
    "CSRF token missing.": "CSRF token missing.",
    "CSRF failed.": "CSRF failed.",
    "CSRF token expired.": "CSRF token expired.",
}

# Patterns for strings that are already in English → copy as-is
ENGLISH_PATTERNS = [
    # Click/WTForms/Werkzeug validation messages
    r"^Missing \w+",
    r"^Invalid \w+",
    r"^Not a valid",
    r"^Number must be",
    r"^Field must be",
    r"^Choices cannot",
    r"^File does not",
    r"^Error: ",
    r"^Option ",
    r"^No such ",
    r"^Try ",
    r"^Could not",
    r"^Couldn't",
    r"^Show ",
    r"^Press any",
    r"^Repeat for",
    r"^Usage:",
    r"^Commands$",
    r"^Options$",
    r"^Value must be",
    r"^This field",
    r"^DeprecationWarning",
    r"^Shell completion",
    r"^Aborted!$",
    r"^A database error",
    r"^An unexpected error",
    r"^No data for",
    r"^Internal server error$",
    r"^Invalid JSON body$",
    r"^Bad request$",
    r"^Invalid numeric value$",
    r"^Invalid date format$",
    r"^Internal error$",
    r"^Unknown error$",
    r"^Access denied",
    r"^Username and",
    r"^Password must be",
    r"^Password updated",
    r"^Failed to update",
    r"^No file part",
    r"^Not a valid",
    r"^\{(name|value|editor|text|param)",
    r"^\%\(prog\)s",
    r"^First page$",
    r"^Last page$",
    r"^Next page$",
    r"^Previous page$",
    r"^Total Bandwidth$",
    r"^Total Requests$",
    r"^unknown error$",
    r"^required$",
    r"^file$",
    r"^path$",
    r"^directory$",
    r"^(default|env var): ",
    r"^Argument \{",
    r"^Choose from",
    r"^Missing \{",
    r'^0"',  # HTML fragments that got extracted
]


def is_already_english(text):
    """Check if a string is already in English."""
    for pattern in ENGLISH_PATTERNS:
        if re.match(pattern, text):
            return True
    return False


def translate_msgid(msgid):
    """Try to translate a msgid."""
    # Direct dictionary match
    if msgid in TRANSLATIONS:
        return TRANSLATIONS[msgid]

    # Already English
    if is_already_english(msgid):
        return msgid

    # Try case-insensitive dictionary match
    msgid_lower = msgid.lower()
    for es, en in TRANSLATIONS.items():
        if es.lower() == msgid_lower:
            return en

    return None


def process_po_file(filepath):
    """Process a .po file and fill in English translations."""
    with open(filepath, encoding="utf-8") as f:
        content = f.read()

    lines = content.split("\n")
    result = []
    i = 0
    translated_count = 0
    untranslated = []
    total_msgids = 0

    while i < len(lines):
        line = lines[i]

        if line.startswith('msgid "'):
            msgid_lines = [line]
            j = i + 1
            while j < len(lines) and lines[j].startswith('"'):
                msgid_lines.append(lines[j])
                j += 1

            # Extract full msgid text
            msgid_text = ""
            for ml in msgid_lines:
                m = re.match(r'(?:msgid )?"(.*)"', ml)
                if m:
                    msgid_text += m.group(1)

            # Skip empty header msgid
            if msgid_text == "":
                for ml in msgid_lines:
                    result.append(ml)
                i = j
                continue

            total_msgids += 1

            # Find corresponding msgstr
            msgstr_idx = j
            if msgstr_idx < len(lines) and lines[msgstr_idx].startswith('msgstr "'):
                m = re.match(r'msgstr "(.*)"', lines[msgstr_idx])
                existing_msgstr = m.group(1) if m else ""

                if not existing_msgstr:
                    translation = translate_msgid(msgid_text)
                    if translation:
                        for ml in msgid_lines:
                            result.append(ml)
                        escaped = translation.replace('"', '\\"')
                        result.append(f'msgstr "{escaped}"')
                        translated_count += 1
                        i = msgstr_idx + 1
                        while i < len(lines) and lines[i].startswith('"'):
                            i += 1
                        continue
                    else:
                        untranslated.append(msgid_text)

            for ml in msgid_lines:
                result.append(ml)
            i = j
            continue

        result.append(line)
        i += 1

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(result))

    return translated_count, total_msgids, untranslated


def main():
    po_file = (
        sys.argv[1] if len(sys.argv) > 1 else "translations/en/LC_MESSAGES/messages.po"
    )
    print(f"Processing: {po_file}")
    translated, total, untranslated = process_po_file(po_file)
    print(f"Translated: {translated}/{total} strings")
    print(f"Remaining: {len(untranslated)} strings need manual translation")
    if untranslated:
        print(f"\nUntranslated strings ({len(untranslated)}):")
        for s in untranslated:
            print(f"  - {s}")


if __name__ == "__main__":
    main()
